### ISSUE TITLE
Clean up users table and re-invite people

### ISSUE THREAD

**Issue by kbalog** [iai-group/arXivDigest#109]

**Comment by oyvi96** [comment]
@kbalog All values in topics table should also be dropped  and rebuilt as some of them contain illegal characters which we decided to not include.

**Comment by kbalog** [comment]
Yes, OK. Let me know once the init topics script has been updated so that I can run it to populate the topics table.

**Comment by kgingstad** [comment]
Think I fixed this in the init_topic_list script earlier, so should be able to just run it. It filters out any topics with invalid characters.

**Comment by kbalog** [comment]
Ok. I assume I need to empty the topics and user_topics tables beforehand.
