### ISSUE TITLE
Update interleaving process for topics

### ISSUE THREAD

**Issue by oyvi96** [iai-group/arXivDigest#114]
* Generalize interleaving method (consider moving interleaving code under `arxivdigest` package, and only minimalistic scripts under `scripts`)

**Comment by oyvi96** [comment]
@kbalog It was decided that if there was a common prefix when multileaving articles, no credit would be given to any system, this worked great when there was no explanations. But now that we have explanations how will we decide which explanation to use for articles in the common prefix. 

The two obvious solutions I see is to either look at the article and explanation as the recommendation meaning that the prefix if only common when the article and explanation is the same (meaning there will be no common prefix almost all the time for articles),
or to pick a random explanation for the elements in the common prefix

PS. Common prefix still works fine for topics

**Comment by oyvi96** [comment]
Should topics be interleaved with just recommendations from the same date or use a weekly pool? 
Seeing that there is no limit to how many topics exist, there shouldn't really be a problem with just interleaving from the previous day.
But of course interleaving from a week is a bit more lenient towards systems.

**Comment by kbalog** [comment]
@oyvi96 When doing the interleaving for articles, we should indeed look at the article and explanation in combination when determining the common prefix (which means basically no common prefix). When computing statistics and evaluation measures, we'll want to consider recommendations both with and without explanations. 

Not sure I understand the question about interleaving topics. Topics don't have a timestamp, i.e., systems can push any number of recommendations. The top-k (say, 10) would be shown to the user upon login for 24-hours; once there is time for a new batch of topic recommendations, just interleave from the highest scoring recommendations from the systems.

**Comment by oyvi96** [comment]
@kbalog Okey, heres a question more related to the user interface for topics then, but it will also affect interleaving.

Users shold be able to accept and reject this list of say 10 topics, and thus making it contain fewer topics for the rest of this day. Will we in anyway try to replenish this list, or will it be more like you get 10 each day and that is it.

Replenishment will probably be a bit difficult to get right as if we interleave more than we show these should ideally be shown the next time, but this would not work as it would change the interleaving order and credits to not be shown as intended.

While dropping not shown interleavings may misrepresent a system so this is not a good idea either. 

One solution that might work is to generate interleavings on user request. But as we discussed earlier then you would want to keep them for seesion, my proposal for that is we could save the last generation date in the database and only update the interleavings on the next day or on explicit refresh requests.

**Comment by kbalog** [comment]
Yes, generate interleavings if (i) the previous one has expired (>24 hours since last web login) or (ii) if the user explicitly requests new recommendations (add "get new recommendations" link/button to topic suggestion box).

**Comment by kbalog** [comment]
Each time the user is given 10 suggestions. Each of these is either accepted or rejected, but we're not filling up the list with new suggestions. Also, once these suggestions expire, they won't be shown again to the user (in fact, these should not even be allowed to be submitted anymore as recommendations via the API); the only way to add them is manually by the user themself.

**Comment by oyvi96** [comment]
@kbalog If we were to just make the api reject those topics it would be really awkward having to try submitting before getting an answer that some of the topics are ineligible. So then we'd at least have to provide an endpoint with all ineligible topics for each user that the system would have to cross-reference. Is this what you're thinking?

**Comment by kbalog** [comment]
We should not allow systems to submit topics that are already returned by the  `/user_feedback/topics` API call.

**Comment by oyvi96** [comment]
Sure, that could work.

**Comment by oyvi96** [comment]
@kbalog if you run the interleaver either for topics or articles  and only one or two systems have valid recommendations (or not enough) should the interleaving still happen, even though the system may get the whole list for itself?

**Comment by kbalog** [comment]
Yes, it should happen.
(That's also the case right now, as there is a single system producing recommendations. This system gets the whole list for itself, but that's OK.)
