### ISSUE TITLE
Allow to suspend notifications

### ISSUE THREAD

**Issue by kbalog** [iai-group/arXivDigest#124]
Once a user is registered, let them "suspend" emails on their profile page by having a "suspended" value for notification period.

There should be an "unsubscribe" link at the bottom of the emails, which would set this with a single click. Then, display the message: "You will no longer receive notifications over email. You can still access recommendations via our web interface."

**Comment by kgingstad** [comment]
can set notification_interval in users to 0

**Comment by kbalog** [comment]
I was thinking the same, yes. But this option should only be offered once they've registered.
