### ISSUE TITLE
Improve logging for baseline recommender

### ISSUE THREAD

**Issue by kbalog** [iai-group/arXivDigest#127]
- Output one line for each user, which is either "User X: recommended Y articles" or "User X: skipped (no topics provided)".
- Drop the line "Unable to make recommendations for the following users..."

**Comment by oyvi96** [comment]
Seemed to be working on master but added more debug messages for debugging on gustav.

Config file now accepts 'log_level' key: 'FATAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG' defaults to info
