### ISSUE TITLE
API crashes on users endpoint

### ISSUE THREAD

**Issue by kbalog** [iai-group/arXivDigest#136]
`mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'inactive' in 'where clause'`

**Comment by kgingstad** [comment]
alter table users
add column inactive boolean default true,
add column activate_trace char(36) unique default null;

Was in the comment on the confirm email pull request. Shoud I send this in an sql script on email?

**Comment by kbalog** [comment]
I missed this, my bad. Ran the sql now. It's a different error now:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where users inactive = 0 ORDER BY user_id ASC LIMIT 0, 10000' at line 1
```

**Comment by kgingstad** [comment]
dont know how this happened, should be 'from users where inactive = 0 order by'...
should i make an issue and fix it right now?

**Comment by kbalog** [comment]
That'd be great, yes. We have the issue already ;) just send a pull request

**Comment by kbalog** [comment]
That solved it, thanks.
