### ISSUE TITLE
Scrape DBLP dump

### ISSUE THREAD

**Issue by kgingstad** [iai-group/arXivDigest#22]
Scrape DBLP dump for titles and create a library of common keywords 
Common keywords can be used to create more accurate and standardized keywords for each author

**Comment by kbalog** [comment]
Future flow:
- offline: download DBLP dump, extract keywords, assign keywords to articles and store them in DB (article_id, title, keyword, score)
- online: when user provides DBLP URL, scrape DBLP page, extract titles (article_id if possible), look up corresponding keywords in DB and aggregate keyword scores; then, present top-10 list as suggested keywords
