### ISSUE TITLE
Match dblp author profile to Semantic Scholar profile

### ISSUE THREAD

**Issue by kgingstad** [iai-group/arXivDigest#38]
- check if it is possible to use dblp author page to find an author on Semantic Scholar
- give users an option to then add the Semantic Scholar profile url to their websites

**Comment by kgingstad** [comment]
- Finds the semantic scholar search link from dblp page or uses a constructed semantic scholar search link to look the author up on semantic scholar
- Tried scraping  the semantic scholar search webpage, but does not work since semantic scholar uses an api call to load information onto the site.
- Tried using this api, but no success. Maybe not allowed/misformed request or missing cookie

**Comment by kbalog** [comment]
For looking up authors, a possible workaround may be to find any paper of the author on DBLP that has a DOI, then look up the paper based on DOI (e.g., https://api.semanticscholar.org/v1/paper/10.1038/nrn3241) and extract the author ID from there.

(There'll likely be multiple authors, so you'd need another round to look up author info (https://api.semanticscholar.org/v1/author/[S2AuthorId]) and then find matching names.

**Comment by oyvi96** [comment]
At the moment we'll just give users the option to add a semantic scholar profile manually. At a later date automatic linking could be interesting, but it will not be a priority for the time being.
