### ISSUE TITLE
Extend scraper/harvester to also fetch info from Semantic Scholar

### ISSUE THREAD

**Issue by kgingstad** [iai-group/arXivDigest#40]
- look up articles in Semantic Scholar to find topics and references
- update database to allow for the extra fields in atricle table
- add extra table with articleid, referenceid

**Comment by kgingstad** [comment]
- Tried scraping webpage, but does not work since semantic scholar uses an api call to load information onto the site.
- Tried using this api, but no success. Maybe not allowed/misformed request or missing cookie

**Comment by kgingstad** [comment]
new papers released on arxiv rss stream not avaiable before 3am our timezone (gmt+1?)

can use the arxiv id to look them up on semantic scholar at this point but not all papers have full information available(references, topics, venues etc..)

**Comment by oyvi96** [comment]
In SS:  396 / 1052
references :  336 / 1052
topics :  214 / 1052
authors :  396 / 1052
venue :  116 / 1052
not in SS :  656 / 1052
Fetching SS data about articles 1 hour after publishing on arXiv, I found that many articles were missing in the SS database and even more was missing some fields.

Results where better the next morning, but there are still many missing fields.

**Comment by kbalog** [comment]
Let's discuss this in person next week.

**Comment by oyvi96** [comment]
Systems will be responsible for collecting this information if they want to use it. Therefore there is no need to retrieve this information in the harvester script.
