### ISSUE TITLE
Websites on profile

### ISSUE THREAD

**Issue by kbalog** [iai-group/arXivDigest#98]
It would be good to accept also http:// and https:// prefixed versions. When ppl copy-paste from the browser bar, it'll contain that. We should actually store the https:// prefixed and normalized ones.

What I mean by normalization:
  - for Semantic Scholar, accept the www. prefixed URL as well, but store it without www.
  - for DBLP, accept the https://dblp.uni-trier.de/ prefix and replace that with https://dblp.org/

**Comment by oyvi96** [comment]
When changing the user object and form, also check that topics only contain  allowed characters, which should be a..z, 0..9, space and dash.
